/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Types;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Conn;
import oracle.net.nt.ConnOption;

/**
 *
 * @author L
 */
public class AddEmployee extends javax.swing.JFrame {

    Connection connect = null;
    CallableStatement c = null;
    ResultSet rs = null;
    Statement s = null;
    private PreparedStatement p;

    DefaultTableModel tblKaryawan = new DefaultTableModel(new Object[]{"ID Karyawan", "Nama", "Alamat", "Jenis Kelamin", "Telepon", "Password"}, 0);

    /**
     * Creates new form AddEmployee
     */
    public AddEmployee() {
        initComponents();
        
        this.setLocationRelativeTo(null);

        btnTambahAdd.setBackground(Color.WHITE);
      

        Conn conn = new Conn();
        conn.setConnections();
        connect = conn.getconnections();

        tampilTableKaryawan();
    }
    
    void tampilTableKaryawan() {
        try {
            String sql = "select * from KARYAWAN order by ID_KARYAWAN";
            p = connect.prepareStatement(sql);
            rs = p.executeQuery();

            tblKaryawan.setRowCount(0);

            String idKar, nama, alamat, jk, telepon, password;

            while (rs.next()) {
                idKar = rs.getString("ID_KARYAWAN");
                nama = rs.getString("NAMA");
                alamat = rs.getString("ALAMAT");
                jk = rs.getString("JENIS_KELAMIN");
                telepon = rs.getString("TELEPON");
                password = rs.getString("PASSWORD");

                tblKaryawan.addRow(new Object[]{idKar, nama, alamat, jk, telepon, password});
            }
            p.close();
            tableKaryawan.setModel(tblKaryawan);
        } catch (SQLException se) {
            System.out.println(se);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfIdAdd = new javax.swing.JTextField();
        tfNamaAdd = new javax.swing.JTextField();
        tfAlamatAdd = new javax.swing.JTextField();
        tfTeleponAdd = new javax.swing.JTextField();
        tfPasswordAdd = new javax.swing.JTextField();
        cbJKAdd = new javax.swing.JComboBox();
        btnTambahAdd = new javax.swing.JButton();
        btnBatalAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableKaryawan = new javax.swing.JTable();
        btnLogoutKaryawan = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        btnTransaksi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Tambah Karyawan");

        jLabel2.setText("ID");

        jLabel3.setText("Nama");

        jLabel4.setText("Alamat");

        jLabel5.setText("Jenis Kelamin");

        jLabel6.setText("Telepon");

        jLabel7.setText("Password");

        cbJKAdd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pria", "Wanita" }));

        btnTambahAdd.setText("Tambah");
        btnTambahAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahAddActionPerformed(evt);
            }
        });

        btnBatalAdd.setText("Batal");

        tableKaryawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableKaryawan);

        btnLogoutKaryawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/log-outResize.png"))); // NOI18N
        btnLogoutKaryawan.setText("Logout");
        btnLogoutKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutKaryawanActionPerformed(evt);
            }
        });

        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        btnTransaksi.setText("Transaksi");
        btnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaksiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cbJKAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfIdAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                        .addComponent(tfNamaAdd)
                        .addComponent(tfAlamatAdd)
                        .addComponent(tfTeleponAdd)
                        .addComponent(tfPasswordAdd)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnBatalAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTambahAdd)))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogoutKaryawan, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnTransaksi)))))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfIdAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfNamaAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfAlamatAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbJKAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfTeleponAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfPasswordAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambahAdd)
                    .addComponent(btnBatalAdd))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogoutKaryawan)
                    .addComponent(jLabel1))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahAddActionPerformed
        // TODO add your handling code here:

        String id_kar = tfIdAdd.getText().toUpperCase();
        String sql;
        try {
            sql = "{call CK_IDKAR(?,?)}";
            c = connect.prepareCall(sql);
            c.setString(1, id_kar);
            c.registerOutParameter(2, Types.INTEGER);
            c.executeUpdate();
            if (c.getInt(2) == 1) {
                JOptionPane.showMessageDialog(null, "Maaf id karyawan sudah digunakan");
            } else {
                sql = "{call ADD_KARYAWAN(?,?,?,?,?,?,?)}";
                c = connect.prepareCall(sql);
                c.setString(1, id_kar);
                c.setString(2, tfNamaAdd.getText().toUpperCase());
                c.setString(3, tfAlamatAdd.getText().toUpperCase());
                c.setString(4, cbJKAdd.getSelectedItem().toString().toUpperCase());
                c.setString(5, tfTeleponAdd.getText());
                c.setString(6, tfPasswordAdd.getText().toUpperCase());
                c.setString(7, "KARYAWAN");
                c.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data karyawan berhasil ditambah");
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
        
        tfIdAdd.setText(null);
        tfNamaAdd.setText(null);
        tfAlamatAdd.setText(null);
        tfTeleponAdd.setText(null);
        tfPasswordAdd.setText(null);
        
        tampilTableKaryawan();
    }//GEN-LAST:event_btnTambahAddActionPerformed

    private void btnLogoutKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutKaryawanActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLogoutKaryawanActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        new Main().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaksiActionPerformed
        // TODO add your handling code here:
        new Transaksi().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTransaksiActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatalAdd;
    private javax.swing.JButton btnLogoutKaryawan;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnTambahAdd;
    private javax.swing.JButton btnTransaksi;
    private javax.swing.JComboBox cbJKAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableKaryawan;
    private javax.swing.JTextField tfAlamatAdd;
    private javax.swing.JTextField tfIdAdd;
    private javax.swing.JTextField tfNamaAdd;
    private javax.swing.JTextField tfPasswordAdd;
    private javax.swing.JTextField tfTeleponAdd;
    // End of variables declaration//GEN-END:variables
}
